#' Calculate and add a calc_wgt_kg column that can be used to multiply catch in 
#' numbers to obtain catch in weight. 
#' 
#' @details
#' This script contains two functions depending on the application: Oregon 
#' historical catches (_HistOR), and Washington historical catches (_HistWA).
#' This function requires inputs from both catch and composition data. Weight
#' data is calculated from the composition data and an `calc_wgt_kg` and
#' `calc_wgt_n` columns are added to the catch data. 
#' 
#' Calculated weight is the average weight by mode and year when mode data exists, 
#' and year when mode data does not exist. For years without weight data, the 
#' overall average (over all modes) is used. Calc_wgt_n is sample size. 
#' 
#' This function has the option to produce a figure showing the weights and sample 
#' sizes. Users should look at this figure to confirm values and assumptions are 
#' appropriate for their species.
#'
#' @section Oregon Historical weights:
#' Weight data is obtained from type 3 MRFSS data (SD509). Only measured weights
#' are used (based on the assumption that measured weights contain two or fewer
#' decimal places and are not zero), only PR/PC modes are applied (MODE_FX = 6 
#' or 7), and ocean areas (AREA_X = 1 - 4). 
#' 
#' MRFSS samples are missing for some years where catch in numbers exist (e.g. 
#' 1979, 1990-1992). Weights are applied for these years based on an overall 
#' average from all years. To help the user determine if this default choice is
#' reasonable for the species being assessed, this function returns a figure 
#' showing the calculated average weight and sample size by year and mode. Should 
#' the user wish to apply a different approach to interpolate, they can with the 
#' information returned from this function.
#' 
#' @section Washington Historical weights:
#' 
#' #to do: Add later
#' 
#' @import patchwork
#' 
#' @export
#' @seealso [clean_catch()] calls 'getWeight_HistOR' and 'getWeight_HistWA'
#' @author Brian Langseth and Ali Whitman
#' @return The data frame from `catch_data` with a new column of calculated 
#' weight by year `calc_wgt_kg`.
#' 
#' 
#' @param catch_data Dataset that contains the state specific historical catch 
#' data as returned by `pull_catch_recfin`.
#' @param bds_data Dataset that contains the weight data as returned by 
#' `pull_bds_recfin`. The current script is coded for type 3 MRFSS data (SD509).
#' @param figure Whether to output a figure showing the average weights 
#' by mode generated by the function in each year that catch is available.
#' Default is TRUE. 
#' @param state The state for which average weights are calculated. Can be
#' "WA" or "OR" for Washington or Oregon historical data, respectively.
#' 

getWeightHist <- function(
    catch_data,
    bds_data,
    figure = TRUE
    state = NULL
) {
  
  if(state = "OR"){
    
    ##
    # Work up biological data
    # - Use only Oregon data, 
    # - Use (assumed to be) directly measured weights that are not zero
    # - Use ocean samples only (AREA_X 1-4)
    # - Use PR/PC modes (MODE_FX = 6-7)
    ##
    
    or_bds <- bds_data |>
      dplyr::filter(ST == 41)
    
    #Add flags to LNGTH (fork length mm), T_LEN (total length mm), and weight 
    #(kg) when these are likely not direct measurements. Direct measurements
    #are assumed to be lengths in mm with no decimals, and weights in kg with
    #more than 2 decimals. Modified from Ali Whitman's code. While SD509 has
    #flags already, these do not appear correct.
    
    #to do: eventually set these up as their own function (getMeasured)
    
    or_bds$lngth_flag <- ifelse(or_bds$LNGTH %in% floor(or_bds$LNGTH),
                          ifelse(is.na(or_bds$LNGTH), "missing", "measured"),
                          "computed")
    
    or_bds$t_len_flag <- ifelse(or_bds$T_LEN %in% floor(or_bds$T_LEN),
                          ifelse(is.na(or_bds$T_LEN), "missing", "measured"),
                          "computed")
    
    or_bds$n_wgt_decimals <- count_decimals(or_bds$WGT) 
    or_bds$wgt_flag <- ifelse(is.na(or_bds$WGT), "missing",
                              ifelse(or_bds$n_wgt_decimals <= 2,"measured","computed"))
    
    #Calculate weight filtering for mode, area, and measured weight
    avg_wgt_mode <- or_bds |>
      dplyr::group_by(YEAR, MODE_FX) |> 
      dplyr::filter(MODE_FX %in% c(6,7),
                    AREA_X %in% c(1:4),
                    wgt_flag == "measured",
                    WGT > 0) |>
      dplyr::summarise(avg_wgt = mean(WGT), 
                       avg_wgt_n = dplyr::n()) |>
      as.data.frame()
    
    avg_wgt_year <- or_bds |>
      dplyr::group_by(YEAR) |> 
      dplyr::filter(MODE_FX %in% c(6,7),
                    AREA_X %in% c(1:4),
                    wgt_flag == "measured",
                    WGT > 0) |>
      dplyr::summarise(avg_wgt = mean(WGT), 
                       avg_wgt_n = dplyr::n()) |>
      as.data.frame()
    
    #Add calculated weight and sample sizes to the catch dataset
    
    #First do it by mode, because the oregon historical reconstruction only
    #has mode starting in 1988. This way mode-specific weights are assigned, and
    #records without modes are assigned as NA.
    temp_catch_data <- dplyr::left_join(
      catch_data, avg_wgt_mode, 
      dplyr::join_by("YEAR" == "YEAR", 
                     "RECFIN_MODE_CODE" == "MODE_FX"))
    
    #Second, replace the NA values for records without modes with yearly averages 
    catch_data <- temp_catch_data |>
      dplyr::left_join(avg_wgt_year, 
                       by = "YEAR") |>
      dplyr::mutate(avg_wgt = dplyr::coalesce(avg_wgt.x, avg_wgt.y)) |>
      dplyr::mutate(avg_wgt_n = dplyr::coalesce(avg_wgt_n.x, avg_wgt_n.y)) |>
      dplyr::select(-avg_wgt.x, -avg_wgt.y, 
                    -avg_wgt_n.x, -avg_wgt_n.y)
    
    #Third, calculate and add an overall average weight across years and modes 
    #for catch records in years where no weight data exist 
    interp_values <- catch_data[is.na(catch_data$avg_wgt), c("YEAR", "RECFIN_MODE_CODE")]
    interp_values$interp_wgt <- mean(catch_data$avg_wgt, na.rm = TRUE) 
    catch_data[is.na(catch_data$avg_wgt), "avg_wgt"] = mean(catch_data$avg_wgt, na.rm = TRUE)
    
    #Output figure of average weight and sample size if user selected to do so
    if(figure){
      
      plot_wgt <- 
        ggplot(catch_data, aes(x = YEAR, y = avg_wgt, 
                             group = RECFIN_MODE_CODE,
                             color = factor(RECFIN_MODE_CODE))) +
        geom_line() + 
        geom_point() +
        scale_color_discrete(
          labels = c("6" = "PC", 
                     "7" = "PR", 
                     "9" = "Not mode specific")) +
        scale_x_continuous(limits = c(1979, 2001)) + 
        labs(color = "") +
        theme(
          legend.position = "inside",
          legend.position.inside = c(0.5, 1.0),
          legend.justification.inside = c(0.5, 1.0),
          legend.direction = "horizontal",
          legend.background = element_blank()) +
        
        #Add in interpolated (overall average) weights
        geom_line(data = interp_values, 
                  aes(x = YEAR, y=interp_wgt), 
                  color = "black") +
        geom_point(data = interp_values, 
                  aes(x = YEAR, y=interp_wgt), 
                  color = "black")

      
      plot_n <- 
        ggplot(catch_data, aes(x = YEAR, y = avg_wgt_n, 
                             group = RECFIN_MODE_CODE,
                             fill = factor(RECFIN_MODE_CODE))) +
        stat_summary(fun = "mean", geom = "bar") + 
        scale_fill_discrete(
          labels = c("6" = "PC", 
                     "7" = "PR", 
                     "9" = "Not mode specific")) +
        scale_x_continuous(limits = c(1979, 2001)) + 
        labs(fill = "") +
        theme(
          legend.position = "inside",
          legend.position.inside = c(0.5, 1.0),
          legend.justification.inside = c(0.5, 1.0),
          legend.direction = "horizontal",
          legend.background = element_blank())
      
      combined_plot <- plot_wgt / plot_n
      
      print(combined_plot)
    }
    

  }
  
  return(catch_data)
}


#Function to count the number of decimal points of a column of numbers
#This function is robust to values without decimal points, whereas
#just using sum with regular expressions is not.

count_decimals <- function(x) {
  # Convert to character representation safely
  x_str <- as.character(x)
  
  # Check if a decimal point actually exists
  has_decimal <- grepl("\\.", x_str)
  
  # Extract digits after point and calculate length
  decimals_only <- sub("^.*\\.", "", x_str)
  
  # Return character length if decimal exists, otherwise return 0
  ifelse(has_decimal, nchar(decimals_only), 0)
}
